config/routes.rb
OpenNebraska::Application.routes.draw do
  
  mount Monologue::Engine, at: '/blog' # or whatever path, be it "/blog" or "/monologue"

  get "static_pages/construction"
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/email"
  get "static_pages/blog"
  get "static_pages/portfolio"
  get "static_pages/register"
  get "static_pages/newsletter"
  

  match '(errors)/:status', to: 'errors#show', constraints: {status: /\d{3}/}
  

  root :to => 'static_pages#construction'

end

app/models/contact.rb
class Contact 
  include ActiveAttr::Model

  attribute :name
  attribute :email
  attribute :subject
  attribute :message
  
  validates :name, 
            :presence => true

  validates :subject, 
            :presence => true

  validates :email, 
            :presence => true

  validates :message, 
            :presence => true
  
  validates :email,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
  
  validates :message,
            :length => { :minimum => 10, :maximum => 1000 }
  
end

app/models/newsletter.rb
# app/models/inquiry.rb
 
class Newsletter 
  include ActiveAttr::Model

  attribute :email
  
  validates :email,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
    
end

app/models/testimony.rb
class Testimony < ActiveRecord::Base
  attr_accessible :content, :screen_name, :tweet_id

  def self.pull_tweets
    Twitter.favorites("railscasts").each do |tweet|
      unless exists?(tweet_id: tweet.id.to_s)
        create!(
          tweet_id: tweet.id.to_s,
          content: tweet.text,
          screen_name: tweet.user.screen_name,
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :create_newsletter, :recent_posts, :all_tags
 
  add_crumb("Home", "/")

  protect_from_forgery

  private
 
    def create_newsletter
     @newsletter = Newsletter.new()
    end

    def recent_posts
      @recent_posts = Monologue::Post.published.limit(3)
    end

    def all_tags
      @tags = Monologue::Tag.order("name").select{|t| t.frequency>0}
      #could use minmax here but it's only supported with ruby > 1.9'
      @tags_frequency_min = @tags.map{|t| t.frequency}.min
      @tags_frequency_max = @tags.map{|t| t.frequency}.max
    end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  
  def show
    @exception = env["action_dispatch.exception"]
    add_crumb "Status Code"
    respond_to do |format|
      format.html { render request.path[1..-1] }
      format.json { render json: {status: request.path[1..-1], error: @exception.message}}
    end
  end

end

app/controllers/monologue/admin/sessions_controller.rb
class Monologue::Admin::SessionsController < Monologue::Admin::BaseController
  skip_before_filter :authenticate_user!
  
  def new
  end

  def create
    user = Monologue::User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:monologue_user_id] = user.id
      redirect_to admin_url, notice: t("monologue.admin.sessions.messages.logged_in")
    else
      flash.now.alert = t("monologue.admin.sessions.messages.invalid")
      render "new"
    end
  end

  def destroy
    session[:monologue_user_id] = nil
    redirect_to main_app.root_path, notice: t("monologue.admin.sessions.messages.logged_out")
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def construction
    render layout: "construction"
  end
  def home
     render layout: "home"
  end
  def about
    add_crumb 'About'
  end
  def contact
    add_crumb 'Contact'
    @contact = Contact.new()
  end
  def email
    add_crumb 'Contact'

    @contact = Contact.new(params[:contact])
    @email = ContactMailer.contact_email(@contact)

    if @contact.valid? && @email.deliver
      render :thank_you
    else
      render :email
    end
  end
  def portfolio
    add_crumb 'Portfolio'
  end
  def newsletter
    @newsletter = Newsletter.new(params[:newsletter])
     if @newsletter.valid?
      ContactMailer.newsletter_email(@newsletter).deliver
      render :newsletter
    else
      render :newsletter_fail
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def construction
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = 'OpenNebraska'
		if page_title.empty?
			base_title
		else
			"#{base_title}:: #{page_title}"
		end
	end

end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/monologue/html_helper.rb
module Monologue
  module HtmlHelper


    # +li+ tag with the 'active' class added if the url is the current one.
    # Eg.:
    #
    #   <%= activable_li_tag users_path do  %>
    #     <%= link_to "Users", users_path %>
    #   <% end %>
    #
    def activable_li_tag(*url, &block)
      content_tag :li, capture(&block), :class => ("active" if url.any?{|u| current_page?(u)})
    end

    # +li+ tag with the 'active' class added if the url is the current one with a link
    # inside it pointing to that url.
    #
    #   <%= activatable_li_tag_with_link "Users", users_path %>
    #
    def activable_li_tag_with_link(title, *url)
      activable_li_tag *url do
        link_to(title, url.first)
      end
    end

    def sidebar_section_for(title, &block)
       content_tag(:section, class: 'widget') do
         content_tag(:header, content_tag(:h3, title)) +
             capture(&block)
       end
     end

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/[if IE 9 ] <html class="ie9" lang="en">
/ [if (gt IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta#view{:content => "width=device-width minimum-scale=1, maximum-scale=1", :name => "viewport"}/
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", :media => "all"
    / Google Fonts
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic&amp;subset=latin,latin-ext", :rel => "stylesheet", :type => "text/css"}/
    / IE Fix for HTML5 Tags
    /[if lt IE 9]
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    = csrf_meta_tags
  %body
    = render :partial => 'shared/region/region1'
    = render :partial => 'shared/region/region2'
    = render :partial => 'shared/region/region3'
    / maincontent
    = render :partial => 'shared/region/region4'
    / End maincontent
    = render :partial => 'shared/region/region9'
    = render :partial => 'shared/region/region10'
    / Back To Top
    %a.scrollup{:href => "#"} Scroll
    / End Back To Top
    = render :partial => 'shared/login'
    / Included JS Files (Compressed)
    = javascript_include_tag "application"

app/views/layouts/construction.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/[if IE 9 ] <html class="ie9" lang="en">
/ [if (gt IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta#view{:content => "width=device-width minimum-scale=1, maximum-scale=1", :name => "viewport"}/
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", :media => "all"
    / Google Fonts
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic&amp;subset=latin,latin-ext", :rel => "stylesheet", :type => "text/css"}/
    / IE Fix for HTML5 Tags
    /[if lt IE 9]
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    = csrf_meta_tags
  %body
    = render :partial => 'shared/region/region1'
    = render :partial => 'shared/region/region2_construction'
    = render :partial => 'shared/region/region3_construction'
    / maincontent
    = render :partial => 'shared/region/region4'
    / End maincontent
    = render :partial => 'shared/region/region9'
    = render :partial => 'shared/region/region10_construction'
    / Back To Top
    %a.scrollup{:href => "#"} Scroll
    / End Back To Top
    = render :partial => 'shared/login'
  / Included JS Files (Compressed)
  = javascript_include_tag "application"
  / Countdown
  = javascript_include_tag "jquery.countdown.js"
  :javascript
    $(function() {
      $('div#clock').countdown("2013/11/10", function(event) {
        var $this = $(this);
        switch(event.type) {
          case "seconds":
          case "minutes":
          case "hours":
          case "days":
          case "weeks":
          case "daysLeft":
            $this.find('span#'+event.type).html(event.value);
            break;
          case "finished":
            $this.hide();
            break;
          }
        });
      });

app/views/layouts/home.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/[if IE 9 ] <html class="ie9" lang="en">
/ [if (gt IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta#view{:content => "width=device-width minimum-scale=1, maximum-scale=1", :name => "viewport"}/
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", :media => "all"
    / Google Fonts
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic&amp;subset=latin,latin-ext", :rel => "stylesheet", :type => "text/css"}/
    / IE Fix for HTML5 Tags
    /[if lt IE 9]
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    = csrf_meta_tags
  %body
    = render :partial => 'shared/region/region1'
    = render :partial => 'shared/region/region2'
    = render :partial => 'shared/region/region3_home'
    / maincontent
    = render :partial => 'shared/region/region4'
    / End maincontent
    = render :partial => 'shared/region/region9'
    = render :partial => 'shared/region/region10'
    / Back To Top
    %a.scrollup{:href => "#"} Scroll
    / End Back To Top
    = render :partial => 'shared/login'
    / Included JS Files (Compressed)
    = javascript_include_tag "application"

app/views/layouts/monologue/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/[if IE 9 ] <html class="ie9" lang="en">
/ [if (gt IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta#view{:content => "width=device-width minimum-scale=1, maximum-scale=1", :name => "viewport"}/
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", :media => "all"
    / Google Fonts
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic&amp;subset=latin,latin-ext", :rel => "stylesheet", :type => "text/css"}/
    / IE Fix for HTML5 Tags
    /[if lt IE 9]
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    = csrf_meta_tags
  %body
    = render :partial => 'shared/region/region1'
    = render :partial => 'shared/region/region2_blog'
    = render :partial => 'shared/region/region3'
    / maincontent
    = render :partial => 'shared/region/region4'
    / End maincontent
    = render :partial => 'shared/region/region9'
    = render :partial => 'shared/region/region10'
    / Back To Top
    %a.scrollup{:href => "#"} Scroll
    / End Back To Top
    = render :partial => 'shared/login'
    / Included JS Files (Compressed)
    = javascript_include_tag "application"

app/views/layouts/monologue/application/_sidebar.html.erb
<% if Monologue.sidebar %>
<!-- Sidebar Widget -->
<aside class="sidebar-widget">
   <% Monologue.sidebar.each do |ext| %>
     <%= render partial: "monologue/sidebar/#{ext}" %>
   <% end %>
</aside>
<!-- End Sidebar Widget -->
<% end %>

app/views/monologue/posts/_post.html.erb
<!-- Begin Article -->
<div class="row">
  <section>
    <%= render partial: 'monologue/posts/post_header', locals: {post: post} %>

    <div class="twelve columns">
      <div class="article_content">
        <%= truncate_html(post.content, length: 375, omission: '') %>
      </div>
      <!-- 
        <div class="tags" data-monologue="tags">
          <%= render post.tags %>
        </div>
       -->
      <%= link_to t("Continue reading"), post.full_url, class: "button small icon-chevron-right" %>
    </div>
</div>
<!-- End  Article -->
<hr class="article_hr"/>

app/views/monologue/posts/_post_header.html.erb
<div class="twelve columns">
  
  <h2 class="article_title"><%= link_to post.title, post.full_url %></h2>

  <div class="article_meta">
    <ul class="link-list">
      <li class="post-date "><span class="icon-calendar"></span><a href="blog-inner.html"><%= I18n.localize(post.published_at.to_date, format: :long) %></a></li>
      <li class="post-author"><span class="icon-user"></span><a href="blog-inner.html"> <%= post.user.name %></a></li>
      <li class="post-categories"><span class="icon-tags"></span><a href="blog-inner.html">Illustrations</a></li>
      <li class="post-comments"><span class="icon-comments"></span> <a href="<%= post.full_url + "#disqus_thread" %>"></a></li>
      </ul>
  </div>
</div>

app/views/monologue/posts/index.html.erb
<%  add_crumb 'Blog' %>
<div class="row maincontent">
  <div class="twelve columns">
    <%= render 'shared/blog_title' %>
  </div>
  <!-- Blog Content -->
  <div class="eight columns">
    <%= render @posts %>
      <!-- Pagination -->
      <div class="row">
        <div class="twelve columns">
          <% if @page %>
            <%= render partial: "pagination" %>
              <% end %>
        </div>
      </div>  
  <!-- End Pagination -->
  </div>
  <!-- End Blog Content -->
  <!-- Sidebar Left -->
  <div class="four columns sidebar-right">
    <%= render 'layouts/monologue/application/sidebar' %>
  </div>
  <!-- End Sidebar Left -->
</div>

app/views/monologue/posts/show.html.erb
<%  add_crumb 'Blog', monologue.root_path %>
<%  add_crumb @post.title %>

<div class="row maincontent">

  <div class="twelve columns">
          
    <%= render 'shared/blog_title' %>
  
  </div>

  <div class="eight columns">
    <!-- Begin Article -->
    <div class="row">
      <% content_for :title do %>
        <%= @post.title %>
      <% end %>

      <% content_for :meta_description do %>
        <%= truncate(strip_tags(@post.content), length: 155) %>
      <% end %>

      <%= render partial: 'monologue/posts/post_header', locals: {post: @post }%>
      <div class="twelve columns">
        <div class="article_content">
          <%= raw @post.content %>
        </div>
      </div>

    	<div class="tags" data-monologue="tags">
        <%= render @post.tags %>
      </div>

      <%= render "monologue/posts/social_sharing" %>

      <div id="disqus_thread"></div>
      <%= render 'layouts/monologue/application/disqus_embed' %>
      <noscript>Please enable JavaScript to view the comments.</noscript>
    </div>
    <!-- End Article -->
  </div>

    <!-- Sidebar Left -->
  <div class="four columns sidebar-right">
    
    <%= render 'layouts/monologue/application/sidebar' %>
    
  </div>
  <!-- End Sidebar Left -->

</div>

app/views/monologue/sidebar/_categories.html.erb
<%= sidebar_section_for(t(".title")) do %>
   <ul>
     <% @tags.each do |tag| %>
       <li id="tag"><%=link_to "#{tag.name} (#{tag.frequency})", tag_url(tag) %> </li>
     <% end %>
   </ul>
 <% end %>

app/views/monologue/sidebar/_latest_posts.html.erb
<%= sidebar_section_for(t(".title")) do  %>
  <ul class="sidebar-list">
    <% @recent_posts.each do |post| %>
      <li>
        <%= link_to post.full_url do %>
          <span class="date"><i class="icon-calendar"></i>
            <%= I18n.localize(post.published_at.to_date, format: :long) %>
          </span>
          <%= post.title %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/monologue/sidebar/_latest_tweets.html.erb
<% unless Monologue.twitter_username.nil? %>
  <%= sidebar_section_for(t(".title")) do %>
    <ul id="latest_tweets">
      <li id="tweet_template" style="display:none;">{{text}}</li>
    </ul>
    <script type="text/javascript" src="https://api.twitter.com/1/statuses/user_timeline/<%= Monologue.twitter_username %>.json?callback=TwitterWidget.callback&amp;count=5"></script>
  <% end %>
<% end %>

app/views/monologue/sidebar/_tag_cloud.html.erb
<%= sidebar_section_for(t(".title")) do  %>
  <% @tags.each do |tag| %>
    <%=link_to tag.name, tag_url(tag), class:label_for_tag(tag,@tags_frequency_min,@tags_frequency_max) %>
  <% end %>
<% end  %>

app/views/shared/_blog_title.html.erb
<div class="page_title">
  <div class="row">
    <div class="twelve columns">
      <h1>
        Welcome to our blog
      </h1>
    </div>
  </div>
</div>

app/views/shared/_breadcrumbs.html.haml
= render_crumbs format: :html_list, ul_class: 'breadcrumbs', last_class: 'current'

app/views/shared/_contact_form.haml
= simple_form_for @contact, url: static_pages_email_path , method:'get', remote: true do |f|
  .row
    .twelve.columns
      = f.error_notification
  .row
    .four.columns
      = f.input :name
    .four.columns
      = f.input :email, as: :email
    .four.columns
      = f.input :subject
  .row
    .twelve.columns
      = f.error :base
      = f.input :message, label: "Message ( 10 characters minimum )", as: :text, input_html: { title: "10 characters minimum", hint: "10 characters minimum"  }
  / %a.medium.button{:href => "#"} Submit
  = f.button :submit, "Submit", class:"medium button"

app/views/shared/_footer.html.haml
/ Footer
.row.footer
  / // // // // // // // // // //
  .four.columns
    %h4 About Us
    %p We say what we do, we do what we say, and we're looking forward to prove it to you.
    %ul.vcard
      %li.address Nebraska, NE. USA
      %li.tel
        %a{:href => "https://github.com/opennebraska"} github.com/opennebraska
      %li.email
        %a{:href => "opennebraska@gmail.com"} opennebraska@gmail.com
  / // // // // // // // // // //
  .four.columns
    %h4 Latest Posts
    %ul.footer-list
      - @recent_posts.each do |post|
        %li
          = link_to post.title, post.full_url 
  / // // // // // // // // // //
  .four.columns
    %h4 Latest Tweets
    - cache "latesttweets#{Date.today}" do
      %ul.footer-list#tweetFeed
        - Testimony.order("tweet_id desc").limit(3).each do |testimony|
          %li
            %a{:href => "#"}= "#{testimony.content} -" 
            %a{:href => "#"}= "@#{testimony.screen_name}"
  / // // // // // // // // // //
/ End Footer

app/views/shared/_login.html.haml
/ Reveal Modal
#Login.reveal-modal.login-modal
  %h2 Login
  %p Please login using your credentials.
  = form_tag monologue.admin_sessions_path do
    %label Username
    = label_tag :email, t(".email")
    = text_field_tag :email, params[:email]
    = label_tag :password, t(".password")
    = password_field_tag :password
    %input.medium.button{:type => "submit", :value => "Login!"}/
  %a.close-reveal-modal ×
/ End Reveal Modal

app/views/shared/_newsletter.html.haml
/ // // // // // // // // // //
#newsletter.eight.columns
  %h2 Sign up for our newsletter
  %p Keep up-to-date with the latest news and updates by subscribing to our newsletter.
/ // // // // // // // // // //
.four.columns
  = simple_form_for @newsletter, url: main_app.static_pages_newsletter_path , method:'get', remote: true do |f|
    .row.collapse.newsletter-input
      .eight.mobile-three.columns
        %p= f.input_field :email, label: false, placeholder: 'Enter email address'
      .four.mobile-one.columns
        = f.button :submit, 'Subscribe', class:'expand', name:'commit'
/ // // // // // // // // // //

app/views/shared/_search.html.haml
.row.collapse.top_search
  .ten.mobile-three.columns
    %input{:placeholder => "Enter search terms", :type => "text"}/
  .two.mobile-one.columns
    %a.button.icon-search{:href => "#"}

app/views/shared/region/_region1.html.haml
/ Region 1 Wrap
.container.region1wrap
  / Top Header
  .row.top_header
    .six.columns
      %ul.link-list
        %li
          %a{:href => "#"} Order Now
        %li
          %a{:href => "#"} Pricing
        %li
          %a{:href => "#"} Site Map
      .login
        %a.button{"data-reveal-id" => "Login", href: "#"} Login
    .six.columns
      %ul.top_social
        %li
          %a.has-tipsy{:href => "http://twitter.com/", :title => "Twitter"}= image_tag "social/Twitter.png"
        %li
          %a.has-tipsy{:href => "http://www.facebook.com/", :title => "Facebook"}= image_tag "social/Facebook.png"
        %li
          %a.has-tipsy{:href => "http://google.com/", :title => "Google"}= image_tag "social/Google.png"
        %li
          %a.has-tipsy{:href => "http://www.LinkedIn.com/", :title => "LinkedIn"}= image_tag "social/LinkedIn.png"
        %li
          %a.has-tipsy{:href => "http://www.Flickr.com/", :title => "Flickr"}= image_tag "social/Flickr.png"
        %li
          %a.has-tipsy{:href => "http://vimeo.com/", :title => "Vimeo"}= image_tag "social/Vimeo.png"
        %li
          %a.has-tipsy{:href => "http://www.rss.com/", :title => "RSS"}= image_tag "social/RSS.png"
  / End Top Header
/ End Region 1 Wrap

app/views/shared/region/_region10.html.haml
/ Region 10 Wrap
.container.region10wrap
  .row.footer_bottom
    / Bottom
    / // // // // // // // // // //
    .six.columns
      %p.copyright © 2012 TouchM by 4GraFx. All rights reserved
    / // // // // // // // // // //
    .six.columns
      %ul.link-list
        %li= link_to "Home", main_app.static_pages_home_path
        %li= link_to "About", main_app.static_pages_about_path
        %li= link_to "Blog", main_app.static_pages_blog_path
        %li= link_to "Portfolio", main_app.static_pages_portfolio_path
        %li= link_to "Contact", main_app.static_pages_contact_path
    / // // // // // // // // // //
    / Bottom
/ End Region 10 Wrap

app/views/shared/region/_region10_construction.html.haml
/ Region 10 Wrap
.container.region10wrap
  .row.footer_bottom
    / Bottom
    / // // // // // // // // // //
    .six.columns
      %p.copyright © 2012 TouchM by 4GraFx. All rights reserved
    / // // // // // // // // // //
    .six.columns
    / // // // // // // // // // //
    / Bottom
/ End Region 10 Wrap

app/views/shared/region/_region2.html.haml
/ Region 2 Wrap
.container.region2wrap
  .row
    / Logo
    .four.columns
      %a#logo{:href => "index.html"}/
      %h1
        Open
        %span Nebraska
    / End Logo
    / Main Navigation
    .eight.columns
      %nav.top-bar
        %ul
          / Toggle Button Mobile
          %li.name
            %h1
              %a{:href => "#"} Please select your page
          %li.toggle-topbar
            %a{:href => "#"}
          / End Toggle Button Mobile
        %section
          / Nav Section
          %ul#nav.right
            %li
              = link_to "Home", main_app.static_pages_home_path, id: 'home_nav', class: ( 'active' if yield(:title) == 'Home')
            %li
              = link_to "About", main_app.static_pages_about_path, id: 'about_nav', class: ( 'active' if yield(:title) == 'About')
            %li
              = link_to "Blog", monologue.root_path, id: 'blog_nav', class: ( 'active' if yield(:title) == 'Blog')
            %li
              = link_to "Portfolio", main_app.static_pages_portfolio_path, id: 'portfolio_nav', class: ( 'active' if yield(:title) == 'Portfolio')
            %li
              = link_to "Contact", main_app.static_pages_contact_path, id: 'contact_nav', class: ( 'active' if yield(:title) == 'Contact')
        / End Nav Section
    / End Main Navigation
/ End Region 2 Wrap

app/views/shared/region/_region2_blog.html.haml
/ Region 2 Wrap
.container.region2wrap
  .row
    / Logo
    .four.columns
      %a#logo{:href => "index.html"}/
      %h1
        Open
        %span Nebraska
    / End Logo
    / Main Navigation
    .eight.columns
      %nav.top-bar
        %ul
          / Toggle Button Mobile
          %li.name
            %h1
              %a{:href => "#"} Please select your page
          %li.toggle-topbar
            %a{:href => "#"}
          / End Toggle Button Mobile
        %section
          / Nav Section
          %ul#nav.right
            %li
              = link_to "Home", main_app.static_pages_home_path, id: 'home_nav', class: ( 'active' if yield(:title) == 'Home')
            %li
              = link_to "About", main_app.static_pages_about_path, id: 'about_nav', class: ( 'active' if yield(:title) == 'About')
            %li
              = link_to "Blog", monologue.root_path, id: 'blog_nav', class: 'active'
            %li
              = link_to "Portfolio", main_app.static_pages_portfolio_path, id: 'portfolio_nav', class: ( 'active' if yield(:title) == 'Portfolio')
            %li
              = link_to "Contact", main_app.static_pages_contact_path, id: 'contact_nav', class: ( 'active' if yield(:title) == 'Contact')
        / End Nav Section
    / End Main Navigation
/ End Region 2 Wrap

app/views/shared/region/_region2_construction.html.haml
/ Region 2 Wrap
.container.region2wrap
  .row
    / Logo
    .four.columns
      %a#logo{href: "index.html"}
        %h1
          Open
          %span Nebraska
    / End Logo
/ End Region 2 Wrap

app/views/shared/region/_region3_construction.html.haml
/ Region 3 Wrap
.container.region3wrap
  / Content Top
  .row.content_top
    .eight.columns.centered
      %h1.construction_title Our Website is Under Construction
  / End Content Top
/ End Region 3 Wrap

app/views/users/newsletter.js.erb
alert('hi')